FROM node:24-alpine3.22 as build

WORKDIR /app/

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build



FROM nginx:alpine as prod

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]






