pipeline{
    agent {
        docker { image 'python:3.10' }
    }

    stages{

        stage('Change directory'){
            steps{
                dir('CI-CD/Jenkins/automate-nightly-backup'){
                    echo "Changed directory"
                } 

            }

        }
            
        stage('Install dependincies') {
            steps{
                sh '''
                python3 -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }
            

        stage('Test') {
            steps{
                sh'''
                source venv/bin/activate
                python3 tests/test.py
                '''
            }
        }

        stage('Build') {
            steps{
                sh'''
                source venv/bin/activate
                python3 app.py
                '''
            }
        }
            
    }
}