pipeline {
    agent any

    stages {
        stage('Build'){
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('CI-CD/Jenkins/first-project'){
                    sh '''
                        ls -la
                        node --version
                        npm --version
                        npm ci
                        npm run build
                        ls -la
                    '''
                }
                   
            }
        }

        stage('Test'){
            steps{
                dir('CI-CD/Jenkins/first-project'){
                    sh '''
                        echo "Test stage"
                    '''
                }
                dir('CI-CD/Jenkins/first-project/build'){
                    sh '''
                        test -f index.html
                    '''
                }
                dir('CI-CD/Jenkins/first-project'){
                    sh '''
                        npm test
                    '''
                }
            }
        }
    }
}